
-- ==============================================================================
-- LUXIFIER V26.0 MASTER SCHEMA
-- ==============================================================================

create extension if not exists "uuid-ossp";

-- 2. TABLAS PRINCIPALES (CORE)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  lumens_balance integer default 50, 
  is_admin boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.credits (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  amount integer not null, 
  description text,
  created_at timestamp with time zone default now()
);

-- 3. BETA DATA GATHERING TABLES
create table if not exists public.beta_uploads (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.profiles(id),
    original_image_path text not null, 
    detected_category text, 
    detected_tags jsonb,
    detected_quality_score integer,
    created_at timestamp with time zone default now()
);

create table if not exists public.beta_generations (
    id uuid default uuid_generate_v4() primary key,
    upload_id uuid references public.beta_uploads(id),
    style_archetype_id text, 
    result_image_path text, 
    full_prompt_payload jsonb, 
    created_at timestamp with time zone default now()
);

create table if not exists public.beta_choices (
    id uuid default uuid_generate_v4() primary key,
    upload_id uuid references public.beta_uploads(id),
    chosen_generation_id uuid references public.beta_generations(id),
    user_feedback text, 
    created_at timestamp with time zone default now()
);

-- 4. BETA WAITLIST
create table if not exists public.beta_waitlist (
    id uuid default uuid_generate_v4() primary key,
    email text not null,
    name text,
    status text default 'pending', 
    ip_address text,
    created_at timestamp with time zone default now()
);

-- 5. POLÍTICAS DE SEGURIDAD (RLS)
-- Limpieza preventiva de políticas para evitar "policy already exists"
do $$ 
begin
    execute 'drop policy if exists "Allow anonymous inserts to waitlist" on public.beta_waitlist';
    execute 'drop policy if exists "Only admins view waitlist" on public.beta_waitlist';
exception when others then null;
end $$;

alter table public.beta_waitlist enable row level security;

create policy "Allow anonymous inserts to waitlist" 
on public.beta_waitlist 
for insert 
with check (true);

create policy "Only admins view waitlist" 
on public.beta_waitlist 
for select 
using (auth.role() = 'service_role' or (select is_admin from public.profiles where id = auth.uid()) = true);
