
-- ==============================================================================
-- LUXIFIER V28.0 SCHEMA
-- ==============================================================================
create extension if not exists "uuid-ossp";

-- ==============================================================================
-- 2. TABLAS PRINCIPALES (CORE)
-- ==============================================================================

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  lumens_balance integer default 50, 
  is_admin boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.credits (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  amount integer not null, 
  description text,
  created_at timestamp with time zone default now()
);

-- ==============================================================================
-- 3. QUEUE MANAGER (SALA DE ESPERA VIRTUAL)
-- ==============================================================================
create table if not exists public.queue_manager (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.profiles(id),
    status text default 'waiting',
    last_heartbeat timestamp with time zone default now(),
    created_at timestamp with time zone default now()
);
create index if not exists idx_queue_created_at on public.queue_manager(created_at);

-- ==============================================================================
-- 4. BETA DATA GATHERING TABLES
-- ==============================================================================

-- WAITING LIST
create table if not exists public.beta_waitlist (
    id uuid default uuid_generate_v4() primary key,
    email text not null,
    name text,
    status text default 'pending', 
    notes text,
    created_at timestamp with time zone default now()
);

-- Tablas de Analítica
create table if not exists public.beta_uploads (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.profiles(id),
    original_image_path text not null, 
    detected_category text, 
    detected_tags jsonb, 
    detected_quality_score integer, 
    created_at timestamp with time zone default now()
);

create table if not exists public.beta_generations (
    id uuid default uuid_generate_v4() primary key,
    upload_id uuid references public.beta_uploads(id),
    style_archetype_id text, 
    result_image_path text, 
    full_prompt_payload jsonb, 
    created_at timestamp with time zone default now()
);

create table if not exists public.beta_choices (
    id uuid default uuid_generate_v4() primary key,
    upload_id uuid references public.beta_uploads(id),
    chosen_generation_id uuid references public.beta_generations(id),
    user_feedback text, 
    created_at timestamp with time zone default now()
);

-- ==============================================================================
-- 5. QUAD-CORE PROTOCOL (4K NATIVE ENGINE)
-- ==============================================================================

create table if not exists public.jobs (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references public.profiles(id),
    status text default 'pending', -- 'pending', 'processing', 'stitching', 'completed', 'failed'
    input_url text,
    final_url text,
    meta jsonb, 
    cost_cogs float,
    created_at timestamp with time zone default now()
);

create table if not exists public.job_tiles (
    id uuid default uuid_generate_v4() primary key,
    job_id uuid references public.jobs(id) on delete cascade,
    quadrant text, 
    storage_path text,
    status text default 'pending',
    created_at timestamp with time zone default now()
);

-- ==============================================================================
-- 6. LEGACY TABLES & MIGRATIONS
-- ==============================================================================
alter table public.generations add column if not exists analysis_data jsonb;
alter table public.variations add column if not exists archetype_id text;

-- FIXED: Add feedback column to prevent PGRST204 error
alter table public.variations add column if not exists feedback text;

-- ==============================================================================
-- 7. POLÍTICAS DE SEGURIDAD (RLS)
-- ==============================================================================
alter table public.beta_uploads enable row level security;
alter table public.beta_generations enable row level security;
alter table public.beta_choices enable row level security;
alter table public.queue_manager enable row level security;
alter table public.beta_waitlist enable row level security;
alter table public.jobs enable row level security;
alter table public.job_tiles enable row level security;

-- Policies (Simplified for setup)
create policy "Users can view own uploads" on public.beta_uploads for select using (auth.uid() = user_id);
create policy "Users can insert own uploads" on public.beta_uploads for insert with check (auth.uid() = user_id);

create policy "Users can view own beta gens" on public.beta_generations for select using (
    exists (select 1 from public.beta_uploads where id = beta_generations.upload_id and user_id = auth.uid())
);
create policy "System can insert beta gens" on public.beta_generations for insert with check (true);

create policy "Users manage own queue slot" on public.queue_manager for all using (auth.uid() = user_id);
create policy "Anyone can read queue count" on public.queue_manager for select using (true);

-- Waitlist Policies
create policy "Anyone can join waitlist" on public.beta_waitlist for insert with check (true);
create policy "Only admin can view waitlist" on public.beta_waitlist for select using (
    exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
);

-- Job Policies
create policy "Users see own jobs" on public.jobs for select using (auth.uid() = user_id);
create policy "System manage jobs" on public.jobs for all using (true);
create policy "Users see own tiles" on public.job_tiles for select using (
    exists (select 1 from public.jobs where id = job_tiles.job_id and user_id = auth.uid())
);
